services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    command: ['redis-server', '--requirepass', 'tj9Z47LRLRzbShNQxFnpPvd5bLpzqZky']
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
